In [1]:
from pathlib import Path

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 200)

DATA_DIR = Path(".")

category_tree = pd.read_csv(DATA_DIR / "category_tree.csv")
events = pd.read_csv(DATA_DIR / "events.csv")
item_properties_1 = pd.read_csv(DATA_DIR / "item_properties_part1.csv")
item_properties_2 = pd.read_csv(DATA_DIR / "item_properties_part2.csv")

item_properties = pd.concat(
    [item_properties_1, item_properties_2],
    ignore_index=True
)

print("Таблица category_tree:", category_tree.shape)
print("Таблица events:", events.shape)
print("Таблица item_properties:", item_properties.shape)

Таблица category_tree: (1669, 2)
Таблица events: (2756101, 5)
Таблица item_properties: (20275902, 4)

In [2]:
def overview(df: pd.DataFrame, name: str) -> None:
    print(f"\n===== {name} =====")
    print("shape:", df.shape)
    display(df.head())
    print("\nТипы:")
    display(df.dtypes.to_frame("dtype"))
    print("\nПропуски:")
    display(df.isna().sum().to_frame("missing_cnt"))
    print("\nДоля пропусков:")
    display((df.isna().mean().mul(100)).round(2).to_frame("missing_pct"))

overview(category_tree, "category_tree")
overview(events, "events")
overview(item_properties, "item_properties")

===== category_tree =====
shape: (1669, 2)

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

Типы:

              dtype
categoryid    int64
parentid    float64

Пропуски:

            missing_cnt
categoryid            0
parentid             25

Доля пропусков:

            missing_pct
categoryid          0.0
parentid            1.5

===== events =====
shape: (2756101, 5)

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

Типы:

                 dtype
timestamp        int64
visitorid        int64
event              str
itemid           int64
transactionid  float64

Пропуски:

               missing_cnt
timestamp                0
visitorid                0
event                    0
itemid                   0
transactionid      2733644

Доля пропусков:

               missing_pct
timestamp             0.00
visitorid             0.00
event                 0.00
itemid                0.00
transactionid        99.19

===== item_properties =====
shape: (20275902, 4)

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513

Типы:

           dtype
timestamp  int64
itemid     int64
property     str
value        str

Пропуски:

           missing_cnt
timestamp            0
itemid               0
property             0
value                0

Доля пропусков:

           missing_pct
timestamp          0.0
itemid             0.0
property           0.0
value              0.0

In [3]:
print("Уникальные события:")
display(events["event"].value_counts(dropna=False))

print("\nЧисло уникальных пользователей:", events["visitorid"].nunique())
print("Число уникальных товаров в events:", events["itemid"].nunique())
print("Число уникальных transactionid:", events["transactionid"].nunique())

print("\nЧисло уникальных товаров в item_properties:", item_properties["itemid"].nunique())
print("Число уникальных свойств:", item_properties["property"].nunique())

Уникальные события:

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

Число уникальных пользователей: 1407580
Число уникальных товаров в events: 235061
Число уникальных transactionid: 17672

Число уникальных товаров в item_properties: 417053
Число уникальных свойств: 1104

In [4]:
events["timestamp"] = pd.to_datetime(events["timestamp"], unit="ms", errors="coerce")
item_properties["timestamp"] = pd.to_datetime(item_properties["timestamp"], unit="ms", errors="coerce")

print("Период events:")
print(events["timestamp"].min(), "->", events["timestamp"].max())

print("\nПериод item_properties:")
print(item_properties["timestamp"].min(), "->", item_properties["timestamp"].max())

Период events:
2015-05-03 03:00:04.384000 -> 2015-09-18 02:59:47.788000

Период item_properties:
2015-05-10 03:00:00 -> 2015-09-13 03:00:00

In [5]:
events.describe(include="all")

,timestamp,visitorid,event,itemid,transactionid
count,2756101,2.756101e+06,2756101,2.756101e+06,22457.000000
unique,NaN,NaN,3,NaN,NaN
top,NaN,NaN,view,NaN,NaN
freq,NaN,NaN,2664312,NaN,NaN
mean,2015-07-09 06:48:08.348000,7.019229e+05,NaN,2.349225e+05,8826.497796
min,2015-05-03 03:00:04.384000,0.000000e+00,NaN,3.000000e+00,0.000000
25%,2015-06-05 04:23:14.792000,3.505660e+05,NaN,1.181200e+05,4411.000000
50%,2015-07-09 14:43:33.599000,7.020600e+05,NaN,2.360670e+05,8813.000000
75%,2015-08-10 16:45:05.168000,1.053437e+06,NaN,3.507150e+05,13224.000000
max,2015-09-18 02:59:47.788000,1.407579e+06,NaN,4.668670e+05,17671.000000
std,NaN,4.056875e+05,NaN,1.341954e+05,5098.996290

In [6]:
category_tree.head(10)

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0
5         231       NaN
6         542     378.0
7        1146     542.0
8        1140     542.0
9        1479    1537.0

In [7]:
item_properties.head(10)

            timestamp  itemid    property                            value
0 2015-06-28 03:00:00  460429  categoryid                             1338
1 2015-09-06 03:00:00  206783         888          1116713 960601 n277.200
2 2015-08-09 03:00:00  395014         400  n552.000 639502 n720.000 424566
3 2015-05-10 03:00:00   59481         790                       n15360.000
4 2015-05-17 03:00:00  156781         917                           828513
5 2015-07-05 03:00:00  285026   available                                0
6 2015-06-14 03:00:00   89534         213                          1121373
7 2015-05-17 03:00:00  264312           6                           319724
8 2015-06-07 03:00:00  229370         202                          1330310
9 2015-06-14 03:00:00   98113         451                  1141052 n48.000

In [8]:
event_dist = (
    events["event"]
    .value_counts(dropna=False)
    .rename_axis("event")
    .reset_index(name="count")
)

event_dist["share_pct"] = (event_dist["count"] / len(events) * 100).round(2)
event_dist

         event    count  share_pct
0         view  2664312      96.67
1    addtocart    69332       2.52
2  transaction    22457       0.81

In [9]:
user_activity = (
    events.groupby("visitorid")
    .size()
    .rename("events_per_user")
    .reset_index()
)

item_activity = (
    events.groupby("itemid")
    .size()
    .rename("events_per_item")
    .reset_index()
)

print("Медианное число событий на пользователя:", user_activity["events_per_user"].median())
print("95-й перцентиль событий на пользователя:", user_activity["events_per_user"].quantile(0.95))
print("99-й перцентиль событий на пользователя:", user_activity["events_per_user"].quantile(0.99))

print("\nМедианное число событий на товар:", item_activity["events_per_item"].median())
print("95-й перцентиль событий на товар:", item_activity["events_per_item"].quantile(0.95))
print("99-й перцентиль событий на товар:", item_activity["events_per_item"].quantile(0.99))

Медианное число событий на пользователя: 1.0
95-й перцентиль событий на пользователя: 5.0
99-й перцентиль событий на пользователя: 13.0

Медианное число событий на товар: 3.0
95-й перцентиль событий на товар: 47.0
99-й перцентиль событий на товар: 143.0

In [10]:
user_event_pivot = (
    events.pivot_table(
        index="visitorid",
        columns="event",
        values="itemid",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

user_event_pivot.head()

event  visitorid  addtocart  transaction  view
0              0          0            0     3
1              1          0            0     1
2              2          0            0     8
3              3          0            0     1
4              4          0            0     1

In [11]:
item_event_pivot = (
    events.pivot_table(
        index="itemid",
        columns="event",
        values="visitorid",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

item_event_pivot.head()

event  itemid  addtocart  transaction  view
0           3          0            0     2
1           4          0            0     3
2           6          0            0    29
3           9          0            0     2
4          15          3            1    18

In [12]:
user_item_pairs = (
    events.groupby(["visitorid", "itemid", "event"])
    .size()
    .rename("cnt")
    .reset_index()
)

user_item_pairs.head()

   visitorid  itemid event  cnt
0          0   67045  view    1
1          0  285930  view    1
2          0  357564  view    1
3          1   72028  view    1
4          2  216305  view    2

In [13]:
pair_event_pivot = (
    user_item_pairs.pivot_table(
        index=["visitorid", "itemid"],
        columns="event",
        values="cnt",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

pair_event_pivot["has_view"] = (pair_event_pivot.get("view", 0) > 0).astype(int)
pair_event_pivot["has_addtocart"] = (pair_event_pivot.get("addtocart", 0) > 0).astype(int)
pair_event_pivot["has_transaction"] = (pair_event_pivot.get("transaction", 0) > 0).astype(int)

pair_event_pivot.head()

event,visitorid,itemid,addtocart,transaction,view,has_view,has_addtocart,has_transaction
0,0,67045,0,0,1,1,0,0
1,0,285930,0,0,1,1,0,0
2,0,357564,0,0,1,1,0,0
3,1,72028,0,0,1,1,0,0
4,2,216305,0,0,2,1,0,0

In [14]:
summary = {
    "user_item_pairs_total": len(pair_event_pivot),
    "pairs_with_view": int(pair_event_pivot["has_view"].sum()),
    "pairs_with_addtocart": int(pair_event_pivot["has_addtocart"].sum()),
    "pairs_with_transaction": int(pair_event_pivot["has_transaction"].sum()),
    "cart_after_view_rate_pct": round(
        100 * pair_event_pivot.loc[pair_event_pivot["has_view"] == 1, "has_addtocart"].mean(), 2
    ),
    "transaction_after_view_rate_pct": round(
        100 * pair_event_pivot.loc[pair_event_pivot["has_view"] == 1, "has_transaction"].mean(), 2
    ),
    "transaction_after_cart_rate_pct": round(
        100 * pair_event_pivot.loc[pair_event_pivot["has_addtocart"] == 1, "has_transaction"].mean(), 2
    ),
}

summary

{'user_item_pairs_total': 2145179,
 'pairs_with_view': 2132127,
 'pairs_with_addtocart': 62025,
 'pairs_with_transaction': 21270,
 'cart_after_view_rate_pct': np.float64(2.32),
 'transaction_after_view_rate_pct': np.float64(0.89),
 'transaction_after_cart_rate_pct': np.float64(30.71)}

In [15]:
property_stats = (
    item_properties.groupby("property")
    .agg(
        rows=("itemid", "size"),
        unique_items=("itemid", "nunique"),
        unique_values=("value", "nunique")
    )
    .sort_values("rows", ascending=False)
    .reset_index()
)

property_stats.head(20)

      property     rows  unique_items  unique_values
0          888  3000398        417053         454723
1          790  1790516        417053          33052
2    available  1503639        417053              2
3   categoryid   788214        417053           1242
4            6   631471        409065           4946
5          283   597419        417053         333165
6          776   574220        407305         328837
7          678   481966        417019           3832
8          364   476486        417053         420554
9          202   448938        414217         279313
10         839   417239        396644           3706
11         917   417227        416171         400893
12         112   417053        417053              1
13         764   417053        417053              1
14         159   417053        417053              1
15         227   347492        328096           4865
16         698   289849        274747           1420
17         451   264416         27094             74
18         663   240813         21563             96
19         962   239372         18799              9

In [16]:
item_properties["value_len"] = item_properties["value"].astype(str).str.len()

item_properties[["value_len"]].describe()

          value_len
count  2.027590e+07
mean   1.765490e+01
std    3.747908e+01
min    1.000000e+00
25%    6.000000e+00
50%    7.000000e+00
75%    1.500000e+01
max    4.550000e+02

In [17]:
item_property_versions = (
    item_properties.groupby(["itemid", "property"])
    .size()
    .rename("versions_cnt")
    .reset_index()
)

item_property_versions["versions_cnt"].describe()

count    1.200381e+07
mean     1.689122e+00
std      3.286474e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.800000e+01
Name: versions_cnt, dtype: float64

In [20]:
from pathlib import Path
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 200)

DATA_DIR = Path(".")

CATEGORY_PATH = DATA_DIR / "category_tree.csv"
EVENTS_PATH = DATA_DIR / "events.csv"
ITEM_PROP_1_PATH = DATA_DIR / "item_properties_part1.csv"
ITEM_PROP_2_PATH = DATA_DIR / "item_properties_part2.csv"
OUTPUT_PATH = DATA_DIR / "EDA_FINDINGS.md"


def safe_pct(num, den):
    if den == 0:
        return 0.0
    return round(100 * num / den, 2)


def series_quantile_safe(s: pd.Series, q: float):
    if len(s) == 0:
        return np.nan
    return s.quantile(q)


def top_n_share(counts: pd.Series, n: int = 10):
    if counts.empty:
        return 0.0
    total = counts.sum()
    if total == 0:
        return 0.0
    return round(100 * counts.sort_values(ascending=False).head(n).sum() / total, 2)


def format_dt(x):
    if pd.isna(x):
        return "NA"
    return pd.Timestamp(x).strftime("%Y-%m-%d %H:%M:%S")


def format_num(x):
    if pd.isna(x):
        return "NA"
    if isinstance(x, (float, np.floating)):
        if float(x).is_integer():
            return f"{int(x):,}".replace(",", " ")
        return f"{x:,.2f}".replace(",", " ")
    if isinstance(x, (int, np.integer)):
        return f"{int(x):,}".replace(",", " ")
    return str(x)


def detect_parent_child_columns(df: pd.DataFrame):
    cols = [c.lower() for c in df.columns]
    parent_col = None
    child_col = None

    for c in df.columns:
        cl = c.lower()
        if "parent" in cl:
            parent_col = c
        if "child" in cl:
            child_col = c

    if parent_col is None and len(df.columns) >= 1:
        parent_col = df.columns[0]
    if child_col is None and len(df.columns) >= 2:
        child_col = df.columns[1]

    return parent_col, child_col


category_tree = pd.read_csv(CATEGORY_PATH)
events = pd.read_csv(EVENTS_PATH)
item_properties_1 = pd.read_csv(ITEM_PROP_1_PATH)
item_properties_2 = pd.read_csv(ITEM_PROP_2_PATH)
item_properties = pd.concat([item_properties_1, item_properties_2], ignore_index=True)

events["timestamp"] = pd.to_datetime(events["timestamp"], unit="ms", errors="coerce")
item_properties["timestamp"] = pd.to_datetime(item_properties["timestamp"], unit="ms", errors="coerce")

parent_col, child_col = detect_parent_child_columns(category_tree)

category_rows = len(category_tree)
category_missing = category_tree.isna().sum().sum()
category_unique_parents = category_tree[parent_col].nunique(dropna=True) if parent_col in category_tree.columns else np.nan
category_unique_children = category_tree[child_col].nunique(dropna=True) if child_col in category_tree.columns else np.nan

events_rows, events_cols = events.shape
events_missing = events.isna().sum().sum()
unique_users = events["visitorid"].nunique(dropna=True)
unique_items_events = events["itemid"].nunique(dropna=True)
unique_transactions = events["transactionid"].nunique(dropna=True)

item_props_rows, item_props_cols = item_properties.shape
item_props_missing = item_properties.isna().sum().sum()
unique_items_props = item_properties["itemid"].nunique(dropna=True)
unique_properties = item_properties["property"].nunique(dropna=True)
unique_property_values = item_properties["value"].nunique(dropna=True)

events_min_ts = events["timestamp"].min()
events_max_ts = events["timestamp"].max()
props_min_ts = item_properties["timestamp"].min()
props_max_ts = item_properties["timestamp"].max()

event_counts = events["event"].value_counts(dropna=False)
event_shares = (event_counts / len(events) * 100).round(2)

views = int(event_counts.get("view", 0))
carts = int(event_counts.get("addtocart", 0))
transactions = int(event_counts.get("transaction", 0))

user_activity = events.groupby("visitorid").size().rename("events_per_user")
item_activity = events.groupby("itemid").size().rename("events_per_item")

median_events_per_user = user_activity.median()
p95_events_per_user = series_quantile_safe(user_activity, 0.95)
p99_events_per_user = series_quantile_safe(user_activity, 0.99)

median_events_per_item = item_activity.median()
p95_events_per_item = series_quantile_safe(item_activity, 0.95)
p99_events_per_item = series_quantile_safe(item_activity, 0.99)

top_10_items_share = top_n_share(item_activity, 10)
top_100_items_share = top_n_share(item_activity, 100)

user_item_pairs = (
    events.groupby(["visitorid", "itemid", "event"])
    .size()
    .rename("cnt")
    .reset_index()
)

pair_event_pivot = (
    user_item_pairs.pivot_table(
        index=["visitorid", "itemid"],
        columns="event",
        values="cnt",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

for col in ["view", "addtocart", "transaction"]:
    if col not in pair_event_pivot.columns:
        pair_event_pivot[col] = 0

pair_event_pivot["has_view"] = (pair_event_pivot["view"] > 0).astype(int)
pair_event_pivot["has_addtocart"] = (pair_event_pivot["addtocart"] > 0).astype(int)
pair_event_pivot["has_transaction"] = (pair_event_pivot["transaction"] > 0).astype(int)

pairs_total = len(pair_event_pivot)
pairs_with_view = int(pair_event_pivot["has_view"].sum())
pairs_with_cart = int(pair_event_pivot["has_addtocart"].sum())
pairs_with_transaction = int(pair_event_pivot["has_transaction"].sum())

cart_after_view_rate = round(
    pair_event_pivot.loc[pair_event_pivot["has_view"] == 1, "has_addtocart"].mean() * 100, 2
) if pairs_with_view > 0 else 0.0

transaction_after_view_rate = round(
    pair_event_pivot.loc[pair_event_pivot["has_view"] == 1, "has_transaction"].mean() * 100, 2
) if pairs_with_view > 0 else 0.0

transaction_after_cart_rate = round(
    pair_event_pivot.loc[pair_event_pivot["has_addtocart"] == 1, "has_transaction"].mean() * 100, 2
) if pairs_with_cart > 0 else 0.0

repeat_views_share = round((pair_event_pivot["view"] > 1).mean() * 100, 2) if len(pair_event_pivot) > 0 else 0.0
repeat_carts_share = round((pair_event_pivot["addtocart"] > 1).mean() * 100, 2) if len(pair_event_pivot) > 0 else 0.0

property_stats = (
    item_properties.groupby("property")
    .agg(
        rows=("itemid", "size"),
        unique_items=("itemid", "nunique"),
        unique_values=("value", "nunique")
    )
    .sort_values("rows", ascending=False)
    .reset_index()
)

top_properties_md = ""
if not property_stats.empty:
    top_properties = property_stats.head(15).copy()
    top_properties_md = top_properties.to_markdown(index=False)
else:
    top_properties_md = "No property stats available"

item_property_versions = (
    item_properties.groupby(["itemid", "property"])
    .size()
    .rename("versions_cnt")
    .reset_index()
)

median_versions_per_item_property = item_property_versions["versions_cnt"].median() if not item_property_versions.empty else np.nan
p95_versions_per_item_property = series_quantile_safe(item_property_versions["versions_cnt"], 0.95) if not item_property_versions.empty else np.nan

items_only_in_events = len(set(events["itemid"].dropna().unique()) - set(item_properties["itemid"].dropna().unique()))
items_only_in_props = len(set(item_properties["itemid"].dropna().unique()) - set(events["itemid"].dropna().unique()))

daily_events = (
    events.assign(date=events["timestamp"].dt.date)
    .groupby(["date", "event"])
    .size()
    .rename("cnt")
    .reset_index()
)

daily_events_md = "No daily events summary"
if not daily_events.empty:
    daily_pivot = daily_events.pivot(index="date", columns="event", values="cnt").fillna(0)
    daily_summary = pd.DataFrame({
        "metric": ["days", "avg_daily_views", "avg_daily_addtocart", "avg_daily_transaction"],
        "value": [
            len(daily_pivot),
            round(daily_pivot["view"].mean(), 2) if "view" in daily_pivot.columns else 0,
            round(daily_pivot["addtocart"].mean(), 2) if "addtocart" in daily_pivot.columns else 0,
            round(daily_pivot["transaction"].mean(), 2) if "transaction" in daily_pivot.columns else 0,
        ]
    })
    daily_events_md = daily_summary.to_markdown(index=False)

implications = []

if carts > 0 and transactions > 0:
    implications.append(
        f'В качестве основного позитивного сигнала разумно использовать "addtocart", '
        f'а покупки применять как более сильный дополнительный сигнал и для пост-фильтрации уже купленных товаров'
    )
else:
    implications.append(
        'Нужно отдельно проверить качество разметки событий, так как позитивные сигналы могут быть слишком редкими'
    )

if top_100_items_share >= 20:
    implications.append(
        f"Наблюдается заметная концентрация популярности товаров: топ-100 товаров дают {top_100_items_share}% всех событий. "
        f"Популярностный baseline обязателен"
    )
else:
    implications.append(
        "Концентрация популярности умеренная, поэтому одного popularity baseline будет недостаточно"
    )

if median_versions_per_item_property and not pd.isna(median_versions_per_item_property) and median_versions_per_item_property > 1:
    implications.append(
        "Свойства товаров обновляются во времени, значит при построении признаков нужно делать temporal snapshot и не допускать утечки из будущего"
    )
else:
    implications.append(
        "Свойства товаров выглядят относительно стабильными и подходят для item feature engineering"
    )

if transaction_after_cart_rate > 20:
    implications.append(
        f"Пары user-item с add-to-cart имеют сильную связь с покупкой: conversion cart->transaction = {transaction_after_cart_rate}%. "
        f"Это подтверждает бизнес-смысл оптимизации add-to-cart"
    )
else:
    implications.append(
        f"Конверсия cart->transaction = {transaction_after_cart_rate}%, поэтому стоит аккуратно проверить согласованность событий и таймлайн"
    )

implications.append(
    "Для офлайн-оценки лучше делать time-based split, а не случайное перемешивание, так как данные событийные и зависят от времени"
)

implications.append(
    "Минимально разумный стек сравнения моделей: popularity baseline, item-to-item co-occurrence или implicit collaborative filtering, затем более сильный ranker для reranking кандидатов"
)

event_distribution_lines = []
for event_name, cnt in event_counts.items():
    share = event_shares.loc[event_name]
    event_distribution_lines.append(f"- {event_name}: {format_num(cnt)} строк, {share}%")

markdown = f"""# EDA Findings

## 1. Data overview

### Tables
- `category_tree.csv`: {format_num(category_rows)} строк, {category_tree.shape[1]} столбцов
- `events.csv`: {format_num(events_rows)} строк, {events_cols} столбцов
- `item_properties.csv` после объединения частей: {format_num(item_props_rows)} строк, {item_props_cols} столбцов

### Missing values
- `category_tree`: {format_num(category_missing)} пропусков всего
- `events`: {format_num(events_missing)} пропусков всего
- `item_properties`: {format_num(item_props_missing)} пропусков всего

### Uniques
- уникальных пользователей в `events`: {format_num(unique_users)}
- уникальных товаров в `events`: {format_num(unique_items_events)}
- уникальных transaction id: {format_num(unique_transactions)}
- уникальных товаров в `item_properties`: {format_num(unique_items_props)}
- уникальных свойств товаров: {format_num(unique_properties)}
- уникальных значений свойств: {format_num(unique_property_values)}

### Category tree
- уникальных parent category: {format_num(category_unique_parents)}
- уникальных child category: {format_num(category_unique_children)}

## 2. Time coverage

- период `events`: {format_dt(events_min_ts)} -> {format_dt(events_max_ts)}
- период `item_properties`: {format_dt(props_min_ts)} -> {format_dt(props_max_ts)}

## 3. Event structure

### Event distribution
{chr(10).join(event_distribution_lines)}

### Daily summary
{daily_events_md}

## 4. User behavior

- медианное число событий на пользователя: {format_num(median_events_per_user)}
- 95-й перцентиль событий на пользователя: {format_num(p95_events_per_user)}
- 99-й перцентиль событий на пользователя: {format_num(p99_events_per_user)}

Интерпретация: если 95-й и 99-й перцентили сильно выше медианы, в данных выражен long tail по активности пользователей.

## 5. Item behavior

- медианное число событий на товар: {format_num(median_events_per_item)}
- 95-й перцентиль событий на товар: {format_num(p95_events_per_item)}
- 99-й перцентиль событий на товар: {format_num(p99_events_per_item)}
- доля событий, приходящаяся на топ-10 товаров: {top_10_items_share}%
- доля событий, приходящаяся на топ-100 товаров: {top_100_items_share}%

Интерпретация: высокая концентрация на небольшом числе товаров означает, что popularity baseline будет сильным и его обязательно нужно включить в сравнение.

## 6. Conversion patterns

- всего уникальных пар user-item: {format_num(pairs_total)}
- пар с просмотром: {format_num(pairs_with_view)}
- пар с add-to-cart: {format_num(pairs_with_cart)}
- пар с transaction: {format_num(pairs_with_transaction)}
- доля пар с add-to-cart среди просмотренных пар: {cart_after_view_rate}%
- доля пар с transaction среди просмотренных пар: {transaction_after_view_rate}%
- доля пар с transaction среди пар с add-to-cart: {transaction_after_cart_rate}%
- доля пар user-item с повторными просмотрами: {repeat_views_share}%
- доля пар user-item с повторными добавлениями в корзину: {repeat_carts_share}%

## 7. Item properties

- медианное число версий на пару item-property: {format_num(median_versions_per_item_property)}
- 95-й перцентиль числа версий на пару item-property: {format_num(p95_versions_per_item_property)}
- товаров только в `events`, но не в `item_properties`: {format_num(items_only_in_events)}
- товаров только в `item_properties`, но не в `events`: {format_num(items_only_in_props)}

### Top properties
{top_properties_md}

Интерпретация: множественные версии свойств по времени означают, что для обучения и инференса нужен снимок признаков на момент события, а не последняя версия из будущего.

## 8. Implications for recommender design

{chr(10).join(f"- {x}" for x in implications)}

## 9. Recommended offline setup

- Целевой сигнал: `addtocart` как основной позитивный event
- Дополнительный сильный позитивный сигнал: `transaction`
- Исключение из рекомендаций: уже купленные товары пользователя
- Разбиение: строго по времени, train на прошлом, validation на будущем
- Базовые метрики: Recall@K, HitRate@K, MAP@K или NDCG@K
- Бизнес-логика: метрики должны отражать способность модели возвращать товары, которые пользователь добавит в корзину
- Минимальный набор baseline-моделей:
  - popularity
  - co-occurrence item-to-item
  - collaborative filtering или retrieval-кандидаты
  - ranker для reranking кандидатов, если успевает по объему проекта

## 10. Risks and constraints

- Возможна сильная разреженность user-item матрицы
- Возможен cold start по товарам и пользователям
- Свойства товаров могут быть шумными и обновляться во времени
- При случайном split возникнет временная утечка
- Нужно заранее определить, какие события считаются позитивными, а какие использовать только как контекст
"""

OUTPUT_PATH.write_text(markdown, encoding="utf-8")

print(f"Готово. Файл сохранён в: {OUTPUT_PATH.resolve()}")
print()
print(markdown[:4000])

Готово. Файл сохранён в: /home/what/praktika/practicum-sem4-praktika2/EDA_FINDINGS.md

# EDA Findings

## 1. Data overview

### Tables
- `category_tree.csv`: 1 669 строк, 2 столбцов
- `events.csv`: 2 756 101 строк, 5 столбцов
- `item_properties.csv` после объединения частей: 20 275 902 строк, 4 столбцов

### Missing values
- `category_tree`: 25 пропусков всего
- `events`: 2 733 644 пропусков всего
- `item_properties`: 0 пропусков всего

### Uniques
- уникальных пользователей в `events`: 1 407 580
- уникальных товаров в `events`: 235 061
- уникальных transaction id: 17 672
- уникальных товаров в `item_properties`: 417 053
- уникальных свойств товаров: 1 104
- уникальных значений свойств: 1 966 868

### Category tree
- уникальных parent category: 362
- уникальных child category: 362

## 2. Time coverage

- период `events`: 2015-05-03 03:00:04 -> 2015-09-18 02:59:47
- период `item_properties`: 2015-05-10 03:00:00 -> 2015-09-13 03:00:00

## 3. Event structure

### Event distribution
- view: 2 664 312 строк, 96.67%
- addtocart: 69 332 строк, 2.52%
- transaction: 22 457 строк, 0.81%

### Daily summary
| metric                |    value |
|:----------------------|---------:|
| days                  |   139    |
| avg_daily_views       | 19167.7  |
| avg_daily_addtocart   |   498.79 |
| avg_daily_transaction |   161.56 |

## 4. User behavior

- медианное число событий на пользователя: 1
- 95-й перцентиль событий на пользователя: 5
- 99-й перцентиль событий на пользователя: 13

Интерпретация: если 95-й и 99-й перцентили сильно выше медианы, в данных выражен long tail по активности пользователей.

## 5. Item behavior

- медианное число событий на товар: 3
- 95-й перцентиль событий на товар: 47
- 99-й перцентиль событий на товар: 143
- доля событий, приходящаяся на топ-10 товаров: 0.75%
- доля событий, приходящаяся на топ-100 товаров: 3.62%

Интерпретация: высокая концентрация на небольшом числе товаров означает, что popularity baseline будет сильным и его обязательно нужно включить в сравнение.

## 6. Conversion patterns

- всего уникальных пар user-item: 2 145 179
- пар с просмотром: 2 132 127
- пар с add-to-cart: 62 025
- пар с transaction: 21 270
- доля пар с add-to-cart среди просмотренных пар: 2.32%
- доля пар с transaction среди просмотренных пар: 0.89%
- доля пар с transaction среди пар с add-to-cart: 30.71%
- доля пар user-item с повторными просмотрами: 14.29%
- доля пар user-item с повторными добавлениями в корзину: 0.24%

## 7. Item properties

- медианное число версий на пару item-property: 1
- 95-й перцентиль числа версий на пару item-property: 1
- товаров только в `events`, но не в `item_properties`: 49 815
- товаров только в `item_properties`, но не в `events`: 231 807

### Top properties
| property   |    rows |   unique_items |   unique_values |
|:-----------|--------:|---------------:|----------------:|
| 888        | 3000398 |         417053 |          454723 |
| 790        | 1790516 |         417053 |           33052 |
| available  | 1503639 |         417053 |               2 |
| categoryid |  788214 |         417053 |            1242 |
| 6          |  631471 |         409065 |            4946 |
| 283        |  597419 |         417053 |          333165 |
| 776        |  574220 |         407305 |          328837 |
| 678        |  481966 |         417019 |            3832 |
| 364        |  476486 |         417053 |          420554 |
| 202        |  448938 |         414217 |          279313 |
| 839        |  417239 |         396644 |            3706 |
| 917        |  417227 |         416171 |          400893 |
| 112        |  417053 |         417053 |               1 |
| 764        |  417053 |         417053 |               1 |
| 159        |  417053 |         417053 |               1 |

Интерпретация: множественные версии свойств по времени означают, что для обучения и инференса нужен снимок признаков на момент события, а не последняя версия из будущего.

## 8. Implications for recommender design

- В качестве основного позитивного сигнала разумно использовать "addtocart", а покупки применять как более си

In [21]:
import json

eda_summary = {
    "tables": {
        "category_tree_rows": int(category_rows),
        "events_rows": int(events_rows),
        "item_properties_rows": int(item_props_rows),
    },
    "uniques": {
        "users": int(unique_users),
        "items_in_events": int(unique_items_events),
        "items_in_properties": int(unique_items_props),
        "properties": int(unique_properties),
        "transactions": int(unique_transactions),
    },
    "time_coverage": {
        "events_min": str(events_min_ts),
        "events_max": str(events_max_ts),
        "properties_min": str(props_min_ts),
        "properties_max": str(props_max_ts),
    },
    "event_counts": {str(k): int(v) for k, v in event_counts.to_dict().items()},
    "event_shares_pct": {str(k): float(v) for k, v in event_shares.to_dict().items()},
    "user_stats": {
        "median_events_per_user": float(median_events_per_user),
        "p95_events_per_user": float(p95_events_per_user),
        "p99_events_per_user": float(p99_events_per_user),
    },
    "item_stats": {
        "median_events_per_item": float(median_events_per_item),
        "p95_events_per_item": float(p95_events_per_item),
        "p99_events_per_item": float(p99_events_per_item),
        "top_10_items_share_pct": float(top_10_items_share),
        "top_100_items_share_pct": float(top_100_items_share),
    },
    "conversion": {
        "pairs_total": int(pairs_total),
        "pairs_with_view": int(pairs_with_view),
        "pairs_with_cart": int(pairs_with_cart),
        "pairs_with_transaction": int(pairs_with_transaction),
        "cart_after_view_rate_pct": float(cart_after_view_rate),
        "transaction_after_view_rate_pct": float(transaction_after_view_rate),
        "transaction_after_cart_rate_pct": float(transaction_after_cart_rate),
        "repeat_views_share_pct": float(repeat_views_share),
        "repeat_carts_share_pct": float(repeat_carts_share),
    },
    "item_properties": {
        "median_versions_per_item_property": None if pd.isna(median_versions_per_item_property) else float(median_versions_per_item_property),
        "p95_versions_per_item_property": None if pd.isna(p95_versions_per_item_property) else float(p95_versions_per_item_property),
        "items_only_in_events": int(items_only_in_events),
        "items_only_in_properties": int(items_only_in_props),
    },
    "implications": implications,
}

json_path = DATA_DIR / "eda_summary.json"
json_path.write_text(json.dumps(eda_summary, ensure_ascii=False, indent=2), encoding="utf-8")

print(f"JSON сохранён в: {json_path.resolve()}")

JSON сохранён в: /home/what/praktika/practicum-sem4-praktika2/eda_summary.json